name: xarray-docs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - scipy
  - bottleneck
  - numpydoc
  - matplotlib
  - seaborn
  - dask
  - ipython
  - sphinx
  - netCDF4
  - cartopy
  - rasterio
  - sphinx-gallery
  - zarr
  - iris
  - flake8
  - cftime
